import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'guide',
      label: '介绍',
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
